[data]
    name = "Juanse"
    email = "zanelli38@gmail.com"  # You should update this with your actual email

[chezmoi]
    sourceDir = "~/.local/share/chezmoi"
    data = true
    umask = 022
    mode = "symlink"
    color = "auto"
    diff = true
    merge = "vimdiff"
    age = "age1mskfegratqv8ge7j5mlg20ydmwgtmum43dcqel8x9mnryj0a73vs2u9skn"
    secret.command = "security find-generic-password -a $USER -s chezmoi-age-key -w"

[chezmoi.template]
    options = ["noescape"] 